Ticket4695 jaws adel
ISISComputingGroup/EPICS-jaws pull request #10
Opened 2019-09-18 14:21 UTC by Alistair-McGann-Tessella

### Description of work

Adds records to copy the archive deadband field (ADEL) from the underlying motors to the jaw blades, gaps and centres. The gaps and centres take their ADEL values from one of the two driving motors, depending on the orientation.

### To test
https://github.com/ISISComputingGroup/IBEX/issues/4695

### Acceptance criteria
- [ ] New records build correctly
- [ ] Jaw blades have ADEL set correctly
- [ ] Gaps and centres have ADEL values set from an appropriate underlying motor

2019-09-23 11:02 UTC, Tom-Willemsen requested changes

2019-09-23 11:02 UTC, Tom-Willemsen commented on jawsApp/Db/jaws.substitutions
> +}
I think a similar block also need to be added to the other substitutions (e.g. split jaws, slits, vertical jaws etc)

2019-09-23 11:02 UTC, Tom-Willemsen commented on jawsApp/Db/jaws.substitutions
> +    {P=\$(P), TO=\$(JAWS)HGAP, FROM=\$(mXE), FIELD=ADEL}
I think `VGAP` copying the `ADEL` from the north axis and ignoring the south axis is fine, but it should be documented on the wiki that this is the behaviour we've chosen.

More generally, can you add a bit about this (specifically for the jaws) to the wiki, just so that we don't get surprised by this behaviour in the future.

2019-09-23 17:28 UTC, Alistair-McGann-Tessella commented on jawsApp/Db/jaws.substitutions
> +    {P=\$(P), TO=\$(JAWS)HGAP, FROM=\$(mXE), FIELD=ADEL}
I have added a paragraph to the jaws wiki page:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Jaws#archive-deadbands

2019-09-24 13:29 UTC, Tom-Willemsen approved these changes

2019-09-24 13:30 UTC, merged